name: CI
on: [push]
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: actions/npm@1.0.0
        with:
          entrypoint: yarn
          args: install --frozen-lockfile
      - name: Test
        uses: actions/npm@1.0.0
        with:
          entrypoint: yarn
          args: test
      - name: Build
        uses: actions/npm@1.0.0
        with:
          entrypoint: yarn
          args: build
